#!/usr/bin/env python3
"""Extract classes + active skills from data/d4data into Cypher seed.

Reads each class's SkillKit (curated active-skill list), joins Power files
for category/tags and StringLists for localized names, and writes
graph/cypher/10-classes-skills.cypher. See graph/ontology.md (v0.1).
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
D4 = ROOT / "data" / "d4data" / "json"
META = D4 / "base" / "meta"
STL = D4 / "enUS_Text" / "meta" / "StringList"
OUT = ROOT / "graph" / "cypher" / "10-classes-skills.cypher"

# SkillKit file base -> class display name (only real playable classes)
CLASSES = {
    "Barbarian": "Barbarian",
    "Druid": "Druid",
    "Necromancer": "Necromancer",
    "Paladin_NEW": "Paladin",
    "Rogue": "Rogue",
    "Sorcerer": "Sorcerer",
    "Spiritborn": "Spiritborn",
    "Warlock": "Warlock",
}


def load(path):
    with open(path) as f:
        return json.load(f)


def stl_name(internal_name):
    """Localized skill name from its StringList, or None."""
    path = STL / f"Power_{internal_name}.stl.json"
    if not path.exists():
        return None
    for entry in load(path).get("arStrings", []):
        if entry.get("szLabel") == "name":
            return entry.get("szText")
    return None


def tag_display(raw):
    """'Skill_Primary_Weapon_Mastery' -> 'Weapon Mastery'; 'Skill_Fire' -> 'Fire'."""
    for prefix in ("Skill_Primary_", "Skill_"):
        if raw.startswith(prefix):
            return raw[len(prefix):].replace("_", " ")
    return raw.replace("_", " ")


def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")


def main():
    if not D4.is_dir():
        sys.exit("data/d4data not found — run ./scripts/fetch-d4data.sh first")

    lines = [
        "// GENERATED by scripts/extract_skills_classes.py — do not edit.",
        f"// Source: d4data game version {(ROOT / 'data/d4data/buildVersion.txt').read_text().strip()}",
        "",
    ]
    skipped = []

    for kit_base, class_name in sorted(CLASSES.items()):
        kit = load(META / "SkillKit" / f"{kit_base}.skl.json")
        pcl = load(META / "PlayerClass" / f"{class_name}.pcl.json")
        class_sno = pcl["__snoID__"]
        lines.append(f"MERGE (c:Class {{snoId: {class_sno}}}) "
                     f"SET c.name = '{esc(class_name)}';")

        for entry in kit.get("arActiveSkillEntries", []):
            internal = entry["snoPower"]["name"]
            sno = entry["snoPower"]["__raw__"]
            level_req = entry.get("nLevelReq", 1)

            pow_path = META / "Power" / f"{internal}.pow.json"
            if not pow_path.exists():
                skipped.append((class_name, internal, "missing Power file"))
                continue
            power = load(pow_path)

            name = stl_name(internal)
            if not name:
                skipped.append((class_name, internal, "no localized name"))
                continue

            primary = (power.get("tPrimaryTag") or {}).get("gbidSkillTag", {}).get("name")
            category = tag_display(primary) if primary else None

            tags = sorted({
                tag_display(t["gbidSkillTag"]["name"])
                for t in power.get("arSkillTags") or []
                if not t.get("bSearchOnly")
                and t.get("gbidSkillTag", {}).get("name", "").startswith("Skill_")
                and not t["gbidSkillTag"]["name"].startswith("Skill_Primary_")
            })

            lines.append(f"MERGE (s:Skill {{snoId: {sno}}}) "
                         f"SET s.name = '{esc(name)}', s.internalName = '{esc(internal)}';")
            lines.append(f"MATCH (c:Class {{snoId: {class_sno}}}), (s:Skill {{snoId: {sno}}}) "
                         f"MERGE (c)-[h:HAS_SKILL]->(s) SET h.levelReq = {level_req};")
            if category:
                lines.append(f"MERGE (:SkillCategory {{name: '{esc(category)}'}});")
                lines.append(f"MATCH (s:Skill {{snoId: {sno}}}), (cat:SkillCategory {{name: '{esc(category)}'}}) "
                             f"MERGE (s)-[:IN_CATEGORY]->(cat);")
            for tag in tags:
                lines.append(f"MERGE (:Tag {{name: '{esc(tag)}'}});")
                lines.append(f"MATCH (s:Skill {{snoId: {sno}}}), (t:Tag {{name: '{esc(tag)}'}}) "
                             f"MERGE (s)-[:TAGGED]->(t);")
        lines.append("")

    OUT.write_text("\n".join(lines) + "\n")
    n_skills = sum(1 for l in lines if l.startswith("MERGE (s:Skill"))
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(CLASSES)} classes, {n_skills} skills")
    for cls, internal, why in skipped:
        print(f"  skipped {cls}/{internal}: {why}", file=sys.stderr)


if __name__ == "__main__":
    main()
